### ISSUE TITLE
[Dev test case] View maze 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#10]
Unit test cases for function "View maze"

**Comment by huilynt** [comment]
Test cases done.

Test Case:
![image](https://user-images.githubusercontent.com/55019350/73764929-bed91200-47ae-11ea-8806-825b99e9098e.png)

Results:
![image](https://user-images.githubusercontent.com/55019350/73768944-db784880-47b4-11ea-8973-8f1666a66c8e.png)

**Comment by cloudsilencer** [comment]
Good work! Pending QA to complete testing
