### ISSUE TITLE
[Dev test case]  Configure current maze 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#11]
Unit test cases for function "Configure current maze"

**Comment by lucastey** [comment]
#20 
Added unit test case file for feature - configure maze

**Comment by cloudsilencer** [comment]
Has the test cases been tested yet? @tayboonkai

**Comment by lucastey** [comment]
Current: 3 Pass, 4 Fail for unit test cases

**Comment by lucastey** [comment]
Updated unit test case codes, pass/fail status unchanged

**Comment by lucastey** [comment]
@cloudsilencer unit testing completion: 7 passing tests, 3 failing tests
#6

**Comment by cloudsilencer** [comment]
Clarified with Boon Kai - 3 failing tests meant there are 3 failing test cases. Overall 100% pass on unit testing. thanks!

**Comment by lucastey** [comment]
<img width="667" alt="Screenshot (382)" src="https://user-images.githubusercontent.com/56620426/74083460-3c4a9e00-4a9f-11ea-953c-8ecf6e92bef8.png">
@cloudsilencer test result screenshot :)
