### ISSUE TITLE
[QA test cases] Display main menu

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#12]
QA test cases for function "Display main menu"

**Comment by cloudsilencer** [comment]
Any updates on the test cases?

**Comment by raijustrai** [comment]
The Display Main Menu QA Test Cases are attached to the file below
[Display Main Menu.xlsx](https://github.com/zseir/ETI_Maze/files/4150630/Display.Main.Menu.xlsx)

**Comment by cloudsilencer** [comment]
Okay, noted with thanks. Please do the necessary testing for this function as soon as possible once the development side is done with its development and unit testing @raijustrai

**Comment by raijustrai** [comment]
I have updated the test case- Added in the test case for the exit option which I had forgotten about in the previous test case 
[Display Main Menu.xlsx](https://github.com/zseir/ETI_Maze/files/4152957/Display.Main.Menu.xlsx)

**Comment by raijustrai** [comment]
I have done the testing for Display Main Menu manually and all tests have passed and some of them have been reconfigured such that the testing will be done when testing for specific functions itself @zseir 
[Display Main Menu.xlsx](https://github.com/zseir/ETI_Maze/files/4153068/Display.Main.Menu.xlsx)

**Comment by cloudsilencer** [comment]
Please display some picture/screenshots as proof of manual testing, thanks @raijustrai

**Comment by huilynt** [comment]
@raijustrai @cloudsilencer Okay, thanks! Will update #2 accordingly.

**Comment by raijustrai** [comment]
Proof of manual testing for Display Main Menu. 
![Display Main Menu 1](https://user-images.githubusercontent.com/58139797/73814003-bf0ff680-481c-11ea-83c6-c0fc4a52a895.JPG)
![Display Main Menu 2](https://user-images.githubusercontent.com/58139797/73814033-d4852080-481c-11ea-93f7-74f6965acdeb.JPG)
