### ISSUE TITLE
[QA Test cases] Read and load maze from file

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#13]
QA Test cases for function "Read and load maze from file"

**Comment by raijustrai** [comment]
The QA Test Case for Read and Load file is attached below. 
[Read and Load File Test Case.xlsx](https://github.com/zseir/ETI_Maze/files/4150644/Read.and.Load.File.Test.Case.xlsx)

**Comment by cloudsilencer** [comment]
Okay, noted with thanks. Please do the necessary testing for this function as soon as possible once the development side is done with its development and unit testing @raijustrai

**Comment by raijustrai** [comment]
Testing for this has been done @zseir 
![Read and Load Test Case](https://user-images.githubusercontent.com/58139797/73801840-b73d5b80-47f6-11ea-954c-e36959f69e7b.JPG)
[Read and Load File Test Case.xlsx](https://github.com/zseir/ETI_Maze/files/4156926/Read.and.Load.File.Test.Case.xlsx)

**Comment by huilynt** [comment]
@raijustrai @cloudsilencer Okay, will update #3 , thank you!
