### ISSUE TITLE
[QA Test cases] View maze 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#14]
QA Test cases for function "View maze"

**Comment by cloudsilencer** [comment]
Any updates on the test cases?

**Comment by raijustrai** [comment]
The View Maze Test Case is as follows 
[View Maze.xlsx](https://github.com/zseir/ETI_Maze/files/4150654/View.Maze.xlsx)

**Comment by cloudsilencer** [comment]
Okay, noted with thanks. Please do the necessary testing for this function as soon as possible once the development side is done with its development and unit testing @raijustrai

**Comment by raijustrai** [comment]
The View Maze Test Case has been done and tested and captured @zseir 
[View Maze.xlsx](https://github.com/zseir/ETI_Maze/files/4156893/View.Maze.xlsx)
![Read and View File](https://user-images.githubusercontent.com/58139797/73801376-3336a400-47f5-11ea-8883-dd03a106fae3.JPG)

**Comment by huilynt** [comment]
@raijustrai @cloudsilencer Okay, will update #4  , thank you!
