### ISSUE TITLE
[QA Test cases] Play maze game

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#15]
QA Test case for function "Play maze game"

**Comment by raijustrai** [comment]
The test case for Play Maze Game is attached below
[Play Maze Game.xlsx](https://github.com/zseir/ETI_Maze/files/4150673/Play.Maze.Game.xlsx)

**Comment by cloudsilencer** [comment]
Okay, noted with thanks. Please do the necessary testing for this function as soon as possible once the development side is done with its development and unit testing @raijustrai

**Comment by cloudsilencer** [comment]
Updated from Meeting 1:
PM to do testing using QA's test cases on 6th Feb

**Comment by cloudsilencer** [comment]
1 
![image](https://user-images.githubusercontent.com/35917911/74082001-57fa7800-4a90-11ea-8621-70ac71b0d220.png)

2
![image](https://user-images.githubusercontent.com/35917911/74082101-8b89d200-4a91-11ea-976b-18c373537c17.png)


3
![image](https://user-images.githubusercontent.com/35917911/74082316-b83ee900-4a93-11ea-92ee-f5941e6ad8ac.png)


4
![image](https://user-images.githubusercontent.com/35917911/74082566-38664e00-4a96-11ea-8edf-1e57e1c98fe1.png)




5
![image](https://user-images.githubusercontent.com/35917911/74082342-e9b7b480-4a93-11ea-9ea4-b0edff199a1b.png)


6
![image](https://user-images.githubusercontent.com/35917911/74082351-0227cf00-4a94-11ea-8372-08f9ff5dbf7f.png)

**Comment by cloudsilencer** [comment]
[Play.Maze.Game.pdf](https://github.com/zseir/ETI_Maze/files/4173968/Play.Maze.Game.pdf)

results of testing done by project manager
