### ISSUE TITLE
[QA Test cases] Configure current maze 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#16]
QA Test cases for function "Configure current maze"

**Comment by raijustrai** [comment]
The Test Cases for Configure Current Maze is as follows: 
[Configure Current Maze.xlsx](https://github.com/zseir/ETI_Maze/files/4150680/Configure.Current.Maze.xlsx)

**Comment by cloudsilencer** [comment]
Okay, noted with thanks. Please do the necessary testing for this function as soon as possible once the development side is done with its development and unit testing @raijustrai

**Comment by cloudsilencer** [comment]
Updated from Meeting 1:
PM to do testing using QA's test cases on 6th Feb

**Comment by cloudsilencer** [comment]
TESTING RESULTS:

![image](https://user-images.githubusercontent.com/35917911/74087669-88123d00-4ac9-11ea-9218-7ff47cb6d411.png)


![image](https://user-images.githubusercontent.com/35917911/74083599-17efc100-4aa1-11ea-8a6f-dfecd1944451.png)

-

![image](https://user-images.githubusercontent.com/35917911/74030805-e61c2300-49ea-11ea-8ea0-533a59079f8d.png)

-

![image](https://user-images.githubusercontent.com/35917911/74031156-bc173080-49eb-11ea-870e-d6ca16046747.png)

ADDITIONAL TEST CASES RESULTS
![image](https://user-images.githubusercontent.com/35917911/74031548-c7b72700-49ec-11ea-8613-69c4cb0b0cf6.png)


TESTING RESULTS AS FOLLOWS:
[Configure.Current.Maze (1).xlsx](https://github.com/zseir/ETI_Maze/files/4174512/Configure.Current.Maze.1.xlsx)
