### ISSUE TITLE
Display Main Menu 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#2]
When the program is run, it should display the main menu as shown in Figure
2. When a user enters an option from 0 to 4, the program will process the option
accordingly. After the option has been processed, the program will display the
main menu again and the process is repeated until the user chooses to exit.

Test Case:
Dev #8 
QA #12

**Comment by cloudsilencer** [comment]
how's the progress for this?

**Comment by huilynt** [comment]
Development and Unit tests done! Assigning @raijustrai for QA testing.

**Comment by huilynt** [comment]
@cloudsilencer Merged successfully by @tayboonkai at 55fc9edc244fea664f61b37937812dd366d57bf1. Issue can be closed!
