### ISSUE TITLE
Read and load maze from file 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#3]
This feature allows the application to read the maze diagram from the data file
and store it in memory. It also stores the start (A) location and the end (B)
location. The application should prompt the user for the name of the data file. 

Test Case:
Dev #9 
QA #13

**Comment by huilynt** [comment]
Done unit tests and development at commit 3bbc6a70c061fcd96ad6d2f3f40b8163c9e9cd1d. @raijustrai  ready for QA testing.

**Comment by huilynt** [comment]
Updated at 294bcce after merging 55fc9ed

**Comment by huilynt** [comment]
Pull Request created at #26, waiting for @tayboonkai or @liewlucas for review and merge.

**Comment by huilynt** [comment]
@cloudsilencer Merged successful at 4de6e7c1ff196873ccce5dd83898fed2b6bb4bd6 by @liewlucas. Issue can be closed!
