### ISSUE TITLE
View maze 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#4]
This feature allows the user to view the stored maze from the list created, the
start and end location done in option 1

Test Case:
Dev #10 
QA #14

**Comment by cloudsilencer** [comment]
any updates for this?

**Comment by huilynt** [comment]
Done unit tests and development at commit 3bbc6a70c061fcd96ad6d2f3f40b8163c9e9cd1d. @raijustrai  ready for QA testing.

**Comment by huilynt** [comment]
Updated at 294bcce after merging 55fc9ed

**Comment by huilynt** [comment]
Pull Request created at #26, waiting for @tayboonkai or @liewlucas for review and merge.

**Comment by cloudsilencer** [comment]
Noted with thanks!
