### ISSUE TITLE
[Dev test case] Play maze game

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#7]
Unit Test cases for function "play maze game"

**Comment by cloudsilencer** [comment]
@liewlucas please provide an update by today, thanks

**Comment by liewlucas** [comment]
added unit test and completed

**Comment by liewlucas** [comment]
5 passing test case and 5 failing test case
100% passed

**Comment by liewlucas** [comment]
@cloudsilencer  unit test is done.

**Comment by liewlucas** [comment]
![playmaze_unittest](https://user-images.githubusercontent.com/39293732/74084573-6013e100-4aab-11ea-9bfa-f8969fbb60a6.PNG)
@cloudsilencer  unit test screenshot :)

**Comment by cloudsilencer** [comment]
thanks for the update!
