### ISSUE TITLE
[Dev test case] Display main menu

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#8]
Unit test cases for function "Display main menu"

**Comment by cloudsilencer** [comment]
@zseir Referring to the issue #2 , the Test cases and testing is done right?

**Comment by huilynt** [comment]
Test cases done! See images below for

Test Case:
![image](https://user-images.githubusercontent.com/55019350/73745916-12d3fe80-478f-11ea-81bb-f44f253eed2b.png)
Results:
![image](https://user-images.githubusercontent.com/55019350/73746072-63e3f280-478f-11ea-9cfe-3697d8a5227f.png)

**Comment by huilynt** [comment]
Edited code and test case after merging 

Test Case:
![image](https://user-images.githubusercontent.com/55019350/73769224-40cc3980-47b5-11ea-9a79-cf427fd5ac6f.png)

Result:
![image](https://user-images.githubusercontent.com/55019350/73769261-55103680-47b5-11ea-995b-21d27d6d75f4.png)

**Comment by cloudsilencer** [comment]
Good work! Pending QA to complete testing
