### ISSUE TITLE
[Dev test cases] Read and load maze from file 

### ISSUE THREAD

**Issue by cloudsilencer** [huilynt/ETI_Maze#9]
Unit test case for function "Read and load maze from file"

**Comment by huilynt** [comment]
Test Case:
![image](https://user-images.githubusercontent.com/55019350/73769330-6fe2ab00-47b5-11ea-8412-b3866acb1be3.png)

Results:
![image](https://user-images.githubusercontent.com/55019350/73768840-aec43100-47b4-11ea-8793-e43d671d88d3.png)

**Comment by cloudsilencer** [comment]
Good work! Pending QA to complete testing
